FROM python:2.7

WORKDIR /app

COPY ./techtrends/ /app/

RUN apt-get update -y && \
    apt-get install -y python-pip python-dev

RUN pip install -r requirements.txt

EXPOSE 3111

RUN python init_db.py

ENTRYPOINT [ "python" ]

CMD [ "app.py" ]
