{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "techtrends.serviceAccountName" . }}
  labels:
{{ include "techtrends.labels" . | indent 4 }}
{{- end -}}
