apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends-deployment
  namespace: sandbox
  labels:
    app: techtrends
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - name: techtrends
        image: muddge/techtrends:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3111
          failureThreshold: 1
          periodSeconds: 60
      # Override pod-level terminationGracePeriodSeconds #
          terminationGracePeriodSeconds: 60
        readinessProbe:
          initialDelaySeconds: 1
          periodSeconds: 2
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
          httpGet:
            scheme: HTTP
            path: /healthz
            port: 3111
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 3111
      imagePullSecrets:
      - name: docker-secret
